name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  release:
    types:
      - created
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GODOT_VERSION: 3.4.4
jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - profile: "Windows Desktop"
            flavour: windows
            executable_name: steel_chalk_asset.exe
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Godot
        uses: vitorgus/setup-godot@v1
        with:
          godot-version: ${{ env.GODOT_VERSION }}
      - name: Export Project
        run: |
          godot --export '${{ matrix.profile }}' '${{ matrix.executable_name }}'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: "steel-chalk-asset-${{ matrix.flavour}}"
          path: ${{ matrix.executable_name }}
