name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  release:
    types:
      - created
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GODOT_VERSION: 3.4.4
jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - profile: Windows Desktop
            flavour: windows
          - profile: Android
            flavour: android
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Godot
        uses: vitorgus/setup-godot@v1
        with:
          godot-version: ${{ env.GODOT_VERSION }}
      - name: Setup Java
        if: ${{ matrix.profile == 'Android' }}
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
      - name: Setup Android SDK
        if: ${{ matrix.profile == 'Android' }}
        uses: android-actions/setup-android@v2
      - name: Setup Android Keystore
        if: ${{ matrix.profile == 'Android' }}
        # Setup debug keystore for now
        run: |
          keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999 -deststoretype pkcs12
      - name: Setup Android SDK Path
        if: ${{ matrix.profile == 'Android' }}
        run: |
          mkdir -p ~/.config/godot
          touch ~/.config/godot/editor_settings-3.tres
          echo 'export/android/android_sdk_path = "/usr/local/lib/android/sdk"' | tee ~/.config/godot/editor_settings-3.tres
      - name: Export Project
        run: |
          godot --path ${{ github.workspace }} --export '${{ matrix.profile }}'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "steel-chalk-asset-${{ matrix.flavour}}"
          path: steel_chalk_asset*
  calculate-version:
    needs:
      - build-and-test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.git-version.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: git-version
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
      - name: Label PR Semantic Minor
        if: ${{ github.event_name == 'pull_request' && steps.git-version.outputs.minor > 0 && steps.git-version.outputs.patch == 0 }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Semver-Minor']
            })
      - name: Label PR Semantic Major
        if: ${{ github.event_name == 'pull_request' && steps.git-version.outputs.major > 0 && steps.git-version.outputs.minor == 0 && steps.git-version.outputs.patch == 0 }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Semver-Major']
            })
  release:
    if: github.ref == 'refs/heads/main'
    needs:
      - build-and-test
      - calculate-version
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        id: download
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.calculate-version.outputs.version }}
          name: Release ${{ needs.calculate-version.outputs.version }}
          generate_release_notes: true
          files: |
            ${{steps.download.outputs.download-path}}/**
