name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  release:
    types:
      - created
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GODOT_VERSION: 3.4.4
jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - profile: "Windows Desktop"
            flavour: windows
            executable_name: steel_chalk_asset.exe
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Godot
        uses: vitorgus/setup-godot@v1
        with:
          godot-version: ${{ env.GODOT_VERSION }}
      - name: Export Project
        run: |
          godot --export '${{ matrix.profile }}' '${{ matrix.executable_name }}'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "steel-chalk-asset-${{ matrix.flavour}}"
          path: ${{ matrix.executable_name }}
  release:
    if: github.ref == 'refs/heads/main'
    needs:
      - build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: git-version
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
      - name: Download build artifacts
        id: download
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.git-version.outputs.semVer }}
          name: Release ${{ steps.git-version.outputs.semVer }}
          files: |
            ${{steps.download.outputs.download-path}}/**
